package osnovna

import (
	"github.com/w-ingsolutions/cms/pkg/phi"
)

func NewRadovi263() map[int]phi.Φ {
	return map[int]phi.Φ{
		0: phi.Φ{
			ID:       1,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":              phi.F{"Title", "Text", "Gletovanje fino malterisanih zidova i plafona, disperzivnim kitom."},
				"Opis":               phi.F{"Opis", "Text", " Površine obrusiti, očistiti i izvršiti neutralizovanje. Pregledati i kitovati manja oštećenja i pukotine. Impregnirati i prevući disperzivni kit tri puta."},
				"Obracun":            phi.F{"Obracun", "Text", "Obračun po m2 gletovane površine."},
				"Jedinica":           phi.F{"Jedinica", "Text", "m2"},
				"Cena":               phi.F{"Cena", "Num", 1.20},
				"Slug":               phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_1"},
				"NeophodanMaterijal": phi.F{"NeophodanMaterijal", "Recept", `[{"id":1,"koeficijent":1}]`},
			},
		},
		1: phi.Φ{
			ID:       2,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":              phi.F{"Title", "Text", "Gletovanje grubo malterisanih zidova i plafona, disperzivnim kitom."},
				"Opis":               phi.F{"Opis", "Text", " Površine obrusiti, očistiti i izvršiti neutralizovanje. Pregledati i kitovati manja oštećenja i pukotine. Impregnirati i prevući disperzivni kit tri puta."},
				"Obracun":            phi.F{"Obracun", "Text", "Obračun po m2 gletovane površine."},
				"Jedinica":           phi.F{"Jedinica", "Text", "m2"},
				"Cena":               phi.F{"Cena", "Num", 1.50},
				"Slug":               phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_2"},
				"NeophodanMaterijal": phi.F{"NeophodanMaterijal", "Recept", `[{"id":1,"koeficijent":1}]`},
			},
		},
		2: phi.Φ{
			ID:       3,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":              phi.F{"Title", "Text", "Gletovanje starih ostruganih zidova i plafona, emulzionim kitom."},
				"Opis":               phi.F{"Opis", "Text", " Sve površine obrusiti, očistiti i izvršiti impregnaciju. Pregledati i kitovati manja oštećenja i pukotine. Kitovati i gletovati emulzionim kitom prvi put. Sve površine fino prebrusiti pa kitovati i gletovati emulzionim kitom drugi put."},
				"Obracun":            phi.F{"Obracun", "Text", "Obračun po m2 gletovane površine."},
				"Jedinica":           phi.F{"Jedinica", "Text", "m2"},
				"Cena":               phi.F{"Cena", "Num", 1.20},
				"Slug":               phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_3"},
				"NeophodanMaterijal": phi.F{"NeophodanMaterijal", "Recept", `[{"id":1,"koeficijent":1}]`},
			},
		},
		3: phi.Φ{
			ID:       4,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":              phi.F{"Title", "Text", "Struganje i gletovanje starih zidova i plafona, emulzionim kitom."},
				"Opis":               phi.F{"Opis", "Text", " Sve površine ostrugati i oprati, a zatim obrusiti, očistiti i izvršiti impregnaciju. Pregledati i kitovati manja oštećenja i pukotine. Kitovati i gletovati emulzionim kitom prvi put. Sve površine fino prebrusiti pa kitovati i gletovati emulzionim kitom drugi put."},
				"Obracun":            phi.F{"Obracun", "Text", "Obračun po m2 gletovane površine."},
				"Jedinica":           phi.F{"Jedinica", "Text", "m2"},
				"Cena":               phi.F{"Cena", "Num", 1.40},
				"Slug":               phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_4"},
				"NeophodanMaterijal": phi.F{"NeophodanMaterijal", "Recept", `[{"id":1,"koeficijent":1}]`},
			},
		},
		4: phi.Φ{
			ID:       5,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":    phi.F{"Title", "Text", "Struganje uljane boje sa zidova."},
				"Opis":     phi.F{"Opis", "Text", " Sve površine ostrugati i oprati."},
				"Obracun":  phi.F{"Obracun", "Text", "Obračun po m2 ostrugane površine."},
				"Jedinica": phi.F{"Jedinica", "Text", "m2"},
				"Cena":     phi.F{"Cena", "Num", 2.00},
				"Slug":     phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_5"},
			},
		},
		5: phi.Φ{
			ID:       6,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":    phi.F{"Title", "Text", "Skidanje postojeće uljane boje sa zidova, paljenjem."},
				"Opis":     phi.F{"Opis", "Text", " Površine obojene uljanom bojom pomoću plina i brenera zagrejati i špahtlama i drugim prigodnim alatkama skinuti. Postupak ponavljati dok se boja ne skine."},
				"Obracun":  phi.F{"Obracun", "Text", "Obračun po m2 ostrugane površine."},
				"Jedinica": phi.F{"Jedinica", "Text", "m2"},
				"Cena":     phi.F{"Cena", "Num", 3.00},
				"Slug":     phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_6"},
			},
		},
		6: phi.Φ{
			ID:       7,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":              phi.F{"Title", "Text", "Lečenje fleka na zidovima i plafonima, bojama na bazi akrilata."},
				"Opis":               phi.F{"Opis", "Text", " Površine sa flekama ostrugati, oprati i gletovati. Bojiti bojama na bazi akrilata više puta."},
				"Obracun":            phi.F{"Obracun", "Text", "Obračun po m2 lečene površine."},
				"Jedinica":           phi.F{"Jedinica", "Text", "m2"},
				"Cena":               phi.F{"Cena", "Num", 3.00},
				"Slug":               phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_7"},
				"NeophodanMaterijal": phi.F{"NeophodanMaterijal", "Recept", `[{"id":3,"koeficijent":1}]`},
			},
		},
		7: phi.Φ{
			ID:       8,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":              phi.F{"Title", "Text", "Bojenje gletovanih zidova i plafona, poludisperzivnim bojama, po izboru projektanta. - Poludisperzivnim bojama."},
				"Opis":               phi.F{"Opis", "Text", " Sve površine brusiti, impregnirati i kitovati manja oštećenja. Predbojiti i ispraviti toniranim disperzionim kitom, a zatim bojiti poludisperzivnom bojom prvi i drugi put."},
				"Obracun":            phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica":           phi.F{"Jedinica", "Text", "m2"},
				"Cena":               phi.F{"Cena", "Num", 0.90},
				"Slug":               phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_8"},
				"NeophodanMaterijal": phi.F{"NeophodanMaterijal", "Recept", `[{"id":0,"koeficijent":1}]`},
			},
		},
		8: phi.Φ{
			ID:       9,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":              phi.F{"Title", "Text", "Bojenje gletovanih zidova i plafona, poludisperzivnim bojama, po izboru projektanta. - Dispererzivnim bojama."},
				"Opis":               phi.F{"Opis", "Text", " Sve površine brusiti, impregnirati i kitovati manja oštećenja. Predbojiti i ispraviti toniranim disperzionim kitom, a zatim bojiti poludisperzivnom bojom prvi i drugi put."},
				"Obracun":            phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica":           phi.F{"Jedinica", "Text", "m2"},
				"Cena":               phi.F{"Cena", "Num", 1.20},
				"Slug":               phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_9"},
				"NeophodanMaterijal": phi.F{"NeophodanMaterijal", "Recept", `[{"id":0,"koeficijent":1}]`},
			},
		},
		9: phi.Φ{
			ID:       10,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":              phi.F{"Title", "Text", "Bojenje fino malterisanih zidova i plafona, poludisperzivnim bojama, bez gletovanja. - Poludisperzivnim bojama."},
				"Opis":               phi.F{"Opis", "Text", " Sve površine brusiti, gipsovati, neutralizovati i impregnirati. Predbojiti poludisperzionom bojom prvi put i ispraviti toniranim disperzionim kitom. Bojiti poludisperzivnom bojom prvi i drugi put. Boja i ton po izboru projektanta."},
				"Obracun":            phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica":           phi.F{"Jedinica", "Text", "m2"},
				"Cena":               phi.F{"Cena", "Num", 0.90},
				"Slug":               phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_10"},
				"NeophodanMaterijal": phi.F{"NeophodanMaterijal", "Recept", `[{"id":0,"koeficijent":1}]`},
			},
		},
		10: phi.Φ{
			ID:       11,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":              phi.F{"Title", "Text", "Bojenje fino malterisanih zidova i plafona, poludisperzivnim bojama, bez gletovanja. - Dispererzivnim bojama."},
				"Opis":               phi.F{"Opis", "Text", " Sve površine brusiti, gipsovati, neutralizovati i impregnirati. Predbojiti poludisperzionom bojom prvi put i ispraviti toniranim disperzionim kitom. Bojiti poludisperzivnom bojom prvi i drugi put. Boja i ton po izboru projektanta."},
				"Obracun":            phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica":           phi.F{"Jedinica", "Text", "m2"},
				"Cena":               phi.F{"Cena", "Num", 1.20},
				"Slug":               phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_11"},
				"NeophodanMaterijal": phi.F{"NeophodanMaterijal", "Recept", `[{"id":1,"koeficijent":1}]`},
			},
		},
		11: phi.Φ{
			ID:       12,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":              phi.F{"Title", "Text", "Bojenje grubo malterisanih zidova i plafona, poludisperzivnim bojama, bez gletovanja. - Poludisperzivnim bojama."},
				"Opis":               phi.F{"Opis", "Text", "Sve površine brusiti, gipsovati, neutralizovati i impregnirati. Predbojiti poludisperzionom bojom prvi put i ispraviti toniranim disperzionim kitom. Bojiti poludisperzivnom bojom prvi i drugi put. Boja i ton po izboru projektanta."},
				"Obracun":            phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica":           phi.F{"Jedinica", "Text", "m2"},
				"Cena":               phi.F{"Cena", "Num", 1.10},
				"Slug":               phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_12"},
				"NeophodanMaterijal": phi.F{"NeophodanMaterijal", "Recept", `[{"id":1,"koeficijent":1}]`},
			},
		},
		12: phi.Φ{
			ID:       13,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":              phi.F{"Title", "Text", "Bojenje grubo malterisanih zidova i plafona, poludisperzivnim bojama, bez gletovanja. - Dispererzivnim bojama."},
				"Opis":               phi.F{"Opis", "Text", "Sve površine brusiti, gipsovati, neutralizovati i impregnirati. Predbojiti poludisperzionom bojom prvi put i ispraviti toniranim disperzionim kitom. Bojiti poludisperzivnom bojom prvi i drugi put. Boja i ton po izboru projektanta."},
				"Obracun":            phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica":           phi.F{"Jedinica", "Text", "m2"},
				"Cena":               phi.F{"Cena", "Num", 1.40},
				"Slug":               phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_13"},
				"NeophodanMaterijal": phi.F{"NeophodanMaterijal", "Recept", `[{"id":1,"koeficijent":1}]`},
			},
		},
		13: phi.Φ{
			ID:       14,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":              phi.F{"Title", "Text", "Bojenje sa gletovanjem zidova, poludisperzivnim bojama. - Poludisperzivnim bojama."},
				"Opis":               phi.F{"Opis", "Text", "Malterisane zidove i plafone gletovati disperzivnim kitom. Površine obrusiti, očistiti i izvršiti neutralizovanje. Pregledati i kitovati manja oštećenja i pukotine. Impregnirati i prevući disperzivni kit tri puta. Sve površine brusiti, impregnirati i kitovati manja oštećenja. Predbojiti i ispraviti toniranim disperzionim kitom, a zatim bojiti poludisperzivnom bojom prvi i drugi put. Boja i ton po izboru projektanta."},
				"Obracun":            phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica":           phi.F{"Jedinica", "Text", "m2"},
				"Cena":               phi.F{"Cena", "Num", 2.00},
				"Slug":               phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_14"},
				"NeophodanMaterijal": phi.F{"NeophodanMaterijal", "Recept", `[{"id":2,"koeficijent":1}]`},
			},
		},
		14: phi.Φ{
			ID:       15,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":              phi.F{"Title", "Text", "Bojenje sa gletovanjem zidova, poludisperzivnim bojama. - Dispererzivnim bojama."},
				"Opis":               phi.F{"Opis", "Text", "Malterisane zidove i plafone gletovati disperzivnim kitom. Površine obrusiti, očistiti i izvršiti neutralizovanje. Pregledati i kitovati manja oštećenja i pukotine. Impregnirati i prevući disperzivni kit tri puta. Sve površine brusiti, impregnirati i kitovati manja oštećenja. Predbojiti i ispraviti toniranim disperzionim kitom, a zatim bojiti poludisperzivnom bojom prvi i drugi put. Boja i ton po izboru projektanta."},
				"Obracun":            phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica":           phi.F{"Jedinica", "Text", "m2"},
				"Cena":               phi.F{"Cena", "Num", 2.20},
				"Slug":               phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_15"},
				"NeophodanMaterijal": phi.F{"NeophodanMaterijal", "Recept", `[{"id":2,"koeficijent":1}]`},
			},
		},
		15: phi.Φ{
			ID:       16,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":              phi.F{"Title", "Text", "Struganje stare boje i bojenje zidova i plafona, poludisperzivnim bojama. - Poludispererzivnim bojama."},
				"Opis":               phi.F{"Opis", "Text", "Sve površine ostrugati i oprati od boje i kita. Brusiti, predimpregnirati, kitovati plastičnim kitom manja oštećenja i kitovati emulzionim kitom. Brusiti, impregnirati i bojiti prvi put, a zatim ispraviti disperzionim kitom manja oštećenja. Bojiti poludisperzivnom bojom prvi i drugi put. Boja i ton po izboru projektanta."},
				"Obracun":            phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica":           phi.F{"Jedinica", "Text", "m2"},
				"Cena":               phi.F{"Cena", "Num", 2.25},
				"Slug":               phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_16"},
				"NeophodanMaterijal": phi.F{"NeophodanMaterijal", "Recept", `[{"id":2,"koeficijent":1}]`},
			},
		},
		16: phi.Φ{
			ID:       17,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":              phi.F{"Title", "Text", "Struganje stare boje i bojenje zidova i plafona, poludisperzivnim bojama. - Dispererzivnim bojama."},
				"Opis":               phi.F{"Opis", "Text", "Sve površine ostrugati i oprati od boje i kita. Brusiti, predimpregnirati, kitovati plastičnim kitom manja oštećenja i kitovati emulzionim kitom. Brusiti, impregnirati i bojiti prvi put, a zatim ispraviti disperzionim kitom manja oštećenja. Bojiti poludisperzivnom bojom prvi i drugi put. Boja i ton po izboru projektanta."},
				"Obracun":            phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica":           phi.F{"Jedinica", "Text", "m2"},
				"Cena":               phi.F{"Cena", "Num", 2.50},
				"Slug":               phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_17"},
				"NeophodanMaterijal": phi.F{"NeophodanMaterijal", "Recept", `[{"id":2,"koeficijent":1}]`},
			},
		},
		17: phi.Φ{
			ID:       18,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":    phi.F{"Title", "Text", "Bojenje gips kartonskih zidova i plafona, poludisperzivnim bojama. - Poludisperzivnim bojama."},
				"Opis":     phi.F{"Opis", "Text", "Glave holšrfova ili eksera minizirati, površine natopiti firnisom i kitovati fuge disperzionim kitom. Bojiti poludisperzivnom bojom prvi put. Ispraviti toniranim disperzionim kitom. Bojiti poludisperzivnom bojom drugi i treći put. Boja i ton po izboru projektanta."},
				"Obracun":  phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica": phi.F{"Jedinica", "Text", "m2"},
				"Cena":     phi.F{"Cena", "Num", 1.00},
				"Slug":     phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_18"},
			},
		},
		18: phi.Φ{
			ID:       19,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":              phi.F{"Title", "Text", "Bojenje gips kartonskih zidova i plafona, poludisperzivnim bojama. - Dispererzivnim bojama."},
				"Opis":               phi.F{"Opis", "Text", "Glave holšrfova ili eksera minizirati, površine natopiti firnisom i kitovati fuge disperzionim kitom. Bojiti poludisperzivnom bojom prvi put. Ispraviti toniranim disperzionim kitom. Bojiti poludisperzivnom bojom drugi i treći put. Boja i ton po izboru projektanta."},
				"Obracun":            phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica":           phi.F{"Jedinica", "Text", "m2"},
				"Cena":               phi.F{"Cena", "Num", 1.25},
				"Slug":               phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_19"},
				"NeophodanMaterijal": phi.F{"NeophodanMaterijal", "Recept", `[{"id":1,"koeficijent":1}]`},
			},
		},
		19: phi.Φ{
			ID:       20,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":    phi.F{"Title", "Text", "Krečenje zidova i plafona četkom, rastvorenim odležalim gašenim krečom."},
				"Opis":     phi.F{"Opis", "Text", "Sve površine okrečiti četkom prvi put, brusiti i gipsovati manja oštećenja i pukotine, a zatim okrečiti drugi put."},
				"Obracun":  phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica": phi.F{"Jedinica", "Text", "m2"},
				"Cena":     phi.F{"Cena", "Num", 0.70},
				"Slug":     phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_20"},
			},
		},
		20: phi.Φ{
			ID:       21,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":    phi.F{"Title", "Text", "Krečenje zidova i plafona, rastvorenim odležalim krečom, četkom i pumpom."},
				"Opis":     phi.F{"Opis", "Text", "Sve površine okrečiti četkom prvi put, brusiti i gipsovati manja oštećenja i pukotine, a zatim okrečiti drugi put. Pumpom prskati prvi i drugi put."},
				"Obracun":  phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica": phi.F{"Jedinica", "Text", "m2"},
				"Cena":     phi.F{"Cena", "Num", 0.90},
				"Slug":     phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_21"},
			},
		},
		21: phi.Φ{
			ID:       22,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":    phi.F{"Title", "Text", "Krečenje sa prskanjem pumpom zidova i plafona, rastvorenim odležalim gašenim krečom, sa dodatkom zemljane boje u prahu, za toniranje."},
				"Opis":     phi.F{"Opis", "Text", "Sve površine okrečiti četkom prvi put, brusiti i gipsovati manja oštećenja i pukotine, a zatim okrečiti drugi put. Brusiti i ispraviti gipsom manja oštećenja i pumpom prskati krečnom bojom prvi i drugi put."},
				"Obracun":  phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica": phi.F{"Jedinica", "Text", "m2"},
				"Cena":     phi.F{"Cena", "Num", 1.00},
				"Slug":     phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_22"},
			},
		},
		22: phi.Φ{
			ID:       23,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":    phi.F{"Title", "Text", "Struganje stare boje i krečenje zidova i plafona četkom, rastvorenim odležalim gašenim krečom."},
				"Opis":     phi.F{"Opis", "Text", "Staru krečnu boju ostrugati i površine brusiti. Sve površine okrečiti četkom prvi put, brusiti i gipsovati manja oštećenja i pukotine, a zatim okrečiti drugi put."},
				"Obracun":  phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica": phi.F{"Jedinica", "Text", "m2"},
				"Cena":     phi.F{"Cena", "Num", 0.90},
				"Slug":     phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_23"},
			},
		},
		23: phi.Φ{
			ID:       24,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":    phi.F{"Title", "Text", "Struganje stare boje i krečenje zidova i plafona četkom i prskanjem, rastvorenim odležalim gašenim krečom. Staru krečnu boju ostrugati i površine brusiti."},
				"Opis":     phi.F{"Opis", "Text", "Sve površine okrečiti četkom prvi put, brusiti i gipsovati manja oštećenja i pukotine. Pumpom prskati prvi i drugi put."},
				"Obracun":  phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica": phi.F{"Jedinica", "Text", "m2"},
				"Cena":     phi.F{"Cena", "Num", 1.20},
				"Slug":     phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_24"},
			},
		},
		24: phi.Φ{
			ID:       25,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":    phi.F{"Title", "Text", "Struganje stare boje i krečenje zidova i plafona pumpom, rastvorenim odležalim gašenim krečom, sa dodatkom zemljane boje u prahu, za toniranje."},
				"Opis":     phi.F{"Opis", "Text", "Staru krečnu boju ostrugati. Sve površine brusiti i krečiti krečnim mlekom. Gipsovati manja oštećenja i pukotine i izvršiti osnovno bojenje. Oštećenja ispraviti gipsom i pokrivno bojiti. Prskati pumpom prvi i drugi put."},
				"Obracun":  phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica": phi.F{"Jedinica", "Text", "m2"},
				"Cena":     phi.F{"Cena", "Num", 1.30},
				"Slug":     phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_25"},
			},
		},
		25: phi.Φ{
			ID:       26,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":    phi.F{"Title", "Text", "Bojenje zidova uljanom bojom."},
				"Opis":     phi.F{"Opis", "Text", "Izvršiti osnovno krečenje, gletovanje i natapanje firnisom. Kitovati i prevući kitom, brusiti, nadkitovati i bojiti uljanom bojom prvi put. Bojiti uljanom bojom drugi put. Boja i ton po izboru projektanta."},
				"Obracun":  phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica": phi.F{"Jedinica", "Text", "m2"},
				"Cena":     phi.F{"Cena", "Num", 3.00},
				"Slug":     phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_26"},
			},
		},
		26: phi.Φ{
			ID:       27,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":    phi.F{"Title", "Text", "Bojenje zidova uljanom bojom, sa lakiranjem."},
				"Opis":     phi.F{"Opis", "Text", "Izvršiti osnovno krečenje, gletovanje i natapanje firnisom. Kitovati i prevući kitom, brusiti, nadkitovati i bojiti uljanom bojom prvi put. Bojiti uljanom bojom drugi put, brusiti i lakirati. Boja i ton po izboru projektanta."},
				"Obracun":  phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica": phi.F{"Jedinica", "Text", "m2"},
				"Cena":     phi.F{"Cena", "Num", 4.00},
				"Slug":     phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_27"},
			},
		},
		27: phi.Φ{
			ID:       28,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":    phi.F{"Title", "Text", "Bojenje starih zidova uljanom bojom, sa kojih je skinuta uljana boja."},
				"Opis":     phi.F{"Opis", "Text", "Oštećenja i pukotine brusiti, kitovati i natopiti firnisom. Predkitovati, kitovati, prevući uljanim kitom, brusiti i nadkitovati. Bojiti uljanom bojom prvi i drugi put. Boja i ton po izboru projektanta."},
				"Obracun":  phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica": phi.F{"Jedinica", "Text", "m2"},
				"Cena":     phi.F{"Cena", "Num", 3.50},
				"Slug":     phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_28"},
			},
		},
		28: phi.Φ{
			ID:       29,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":    phi.F{"Title", "Text", "Bojenje starih zidova uljanom bojom, sa lakiranjem, sa kojih je skinuta uljana boja."},
				"Opis":     phi.F{"Opis", "Text", "Oštećenja i pukotine brusiti, kitovati i natopiti firnisom. Predkitovati, kitovati, prevući uljanim kitom, brusiti i nadkitovati. Bojiti uljanom bojom prvi i drugi put. Nadkitovati i lakirati. Boja i ton po izboru projektanta."},
				"Obracun":  phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica": phi.F{"Jedinica", "Text", "m2"},
				"Cena":     phi.F{"Cena", "Num", 4.25},
				"Slug":     phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_29"},
			},
		},
		29: phi.Φ{
			ID:       30,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":    phi.F{"Title", "Text", "Bojenje starih zidova uljanom bojom, preko stare uljane boje."},
				"Opis":     phi.F{"Opis", "Text", "Zidove očistiti i oprati deterdžentom. Brusiti, kitovati oštećenja i pukotine, predbojiti i zakitovati podlogu. Nadkitovati uljanim kitom. Brusiti i bojiti drugi put uljanom bojom. Bojiti uljanom bojom treći put. Boja i ton po izboru projektanta."},
				"Obracun":  phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica": phi.F{"Jedinica", "Text", "m2"},
				"Cena":     phi.F{"Cena", "Num", 3.75},
				"Slug":     phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_30"},
			},
		},
		30: phi.Φ{
			ID:       31,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":    phi.F{"Title", "Text", "Bojenje starih zidova uljanom bojom, preko stare uljane boje sa lakom."},
				"Opis":     phi.F{"Opis", "Text", "Zidove očistiti i oprati deterdžentom. Brusiti, kitovati oštećenja i pukotine, predbojiti i zakitovati podlogu. Kitovati i prevući kit. Bojiti uljanom bojom prvi i drugi put. Brusiti i nadkitovati lak kitom i lakirati. Boja i ton po izboru projektanta."},
				"Obracun":  phi.F{"Obracun", "Text", "Obračun po m2 obojene površine."},
				"Jedinica": phi.F{"Jedinica", "Text", "m2"},
				"Cena":     phi.F{"Cena", "Num", 4.00},
				"Slug":     phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_31"},
			},
		},
		31: phi.Φ{
			ID:       32,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":              phi.F{"Title", "Text", "Obrada unutrašnjih zidova dekorativnim materijalom, španski zid, Prvi maj Čačak."},
				"Opis":               phi.F{"Opis", "Text", "Podloga mora da bude čvrsta i čista bez prašine i masnoća. Podlogu impregnirati Podlogom-A Pripremljen materijal naneti na zid metalnom glet hoblom u debljini do 5 mm.  Nanetu masu dekorativno obraditi gumenim ili sunđerastim valjkom, strukture po izboru projektanta."},
				"Obracun":            phi.F{"Obracun", "Text", "Obračun po m2 obrađene površine."},
				"Jedinica":           phi.F{"Jedinica", "Text", "m2"},
				"Cena":               phi.F{"Cena", "Num", 3.50},
				"Slug":               phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_32"},
				"NeophodanMaterijal": phi.F{"NeophodanMaterijal", "Recept", `[{"id":5,"koeficijent":1}]`},
			},
		},
		32: phi.Φ{
			ID:       33,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":    phi.F{"Title", "Text", "Obrada unutrašnjih zidova dekorativnim malterom, Termogal, Galenika - Magmasil."},
				"Opis":     phi.F{"Opis", "Text", "Podloga mora da bude čvrsta, bez trošnih delova, čista bez prašine i masnoća. Pripremljen materijal naneti na zid valjkom, strukture po izboru projektanta."},
				"Obracun":  phi.F{"Obracun", "Text", "Obračun po m2 obrađene površine."},
				"Jedinica": phi.F{"Jedinica", "Text", "m2"},
				"Cena":     phi.F{"Cena", "Num", 3.50},
				"Slug":     phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_33"},
			},
		},
		33: phi.Φ{
			ID:       34,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":              phi.F{"Title", "Text", "Izrada linkrusta, španskog zida, sitnijeg, tehnikom po izboru projektanta. - Sitniji."},
				"Opis":               phi.F{"Opis", "Text", "Sve površine brusiti i impregnirati, predkitovati disperzivnim kitom. Prevući disperzivnim kitom i reljefno, rustično, obraditi površine po izboru projektanta (četkom, valjkom, oblom, itd). Linskrust završno obojiti i impregnirati."},
				"Obracun":            phi.F{"Obracun", "Text", "Obračun po m2 obrađene površine."},
				"Jedinica":           phi.F{"Jedinica", "Text", "m2"},
				"Cena":               phi.F{"Cena", "Num", 2.50},
				"Slug":               phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_34"},
				"NeophodanMaterijal": phi.F{"NeophodanMaterijal", "Recept", `[{"id":2,"koeficijent":1}]`},
			},
		},
		34: phi.Φ{
			ID:       35,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":              phi.F{"Title", "Text", "Izrada linkrusta, španskog zida, sitnijeg, tehnikom po izboru projektanta. - Srednji."},
				"Opis":               phi.F{"Opis", "Text", "Sve površine brusiti i impregnirati, predkitovati disperzivnim kitom. Prevući disperzivnim kitom i reljefno, rustično, obraditi površine po izboru projektanta (četkom, valjkom, oblom, itd). Linskrust završno obojiti i impregnirati."},
				"Obracun":            phi.F{"Obracun", "Text", "Obračun po m2 obrađene površine."},
				"Jedinica":           phi.F{"Jedinica", "Text", "m2"},
				"Cena":               phi.F{"Cena", "Num", 3.75},
				"Slug":               phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_35"},
				"NeophodanMaterijal": phi.F{"NeophodanMaterijal", "Recept", `[{"id":3,"koeficijent":1}]`},
			},
		},
		35: phi.Φ{
			ID:       36,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":              phi.F{"Title", "Text", "Izrada linkrusta, španskog zida, sitnijeg, tehnikom po izboru projektanta. - Krupniji."},
				"Opis":               phi.F{"Opis", "Text", "Sve površine brusiti i impregnirati, predkitovati disperzivnim kitom. Prevući disperzivnim kitom i reljefno, rustično, obraditi površine po izboru projektanta (četkom, valjkom, oblom, itd). Linskrust završno obojiti i impregnirati."},
				"Obracun":            phi.F{"Obracun", "Text", "Obračun po m2 obrađene površine."},
				"Jedinica":           phi.F{"Jedinica", "Text", "m2"},
				"Cena":               phi.F{"Cena", "Num", 5.00},
				"Slug":               phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_36"},
				"NeophodanMaterijal": phi.F{"NeophodanMaterijal", "Recept", `[{"id":5,"koeficijent":1}]`},
			},
		},
		36: phi.Φ{
			ID:       37,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":    phi.F{"Title", "Text", "Obrada zidova plastičnim malterom (Bavalit)prskanjem."},
				"Opis":     phi.F{"Opis", "Text", "Vrsta i boje po izboru projektanta. Zidna podloga mora biti zdrava i suva. Podlogu očistiti i impregnirati izolacionom masom radi bolje veze. Naneti molerskom četkom u jednom sloju, a ako podloga jako upija premazati dva puta. Na osušenu podlogu naneti malter, napravljen i dobro izmešan da se dobije jednolična i konzistentna masa. Plastični malter se nanosi pomoću ježa ili kompresora sa pištoljem. Prskanje se vrši 2-3 puta, odnosno da plastični malter ravnomerno pokrije površinu i da dobije jednoličan izgled u tonu i strukturi. Otvore i drugo zaštititi PVC folijom što ulazi u cenu, ali se otvori ne odbijaju od površine zidova."},
				"Obracun":  phi.F{"Obracun", "Text", "Obračun po m2 obrađene površine."},
				"Jedinica": phi.F{"Jedinica", "Text", "m2"},
				"Cena":     phi.F{"Cena", "Num", 3.50},
				"Slug":     phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_37"},
			},
		},
		37: phi.Φ{
			ID:       38,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":    phi.F{"Title", "Text", "Obrada zidova plastičnim malterom (Bavalit)prskanjem."},
				"Opis":     phi.F{"Opis", "Text", "Vrsta i boje po izboru projektanta. Zidna podloga mora biti zdrava i suva. Podlogu očistiti i impregnirati izolacionom masom radi bolje veze. Naneti molerskom četkom u jednom sloju, a ako podloga jako upija premazati dva puta. Na osušenu podlogu naneti malter, napravljen i dobro izmešan da se dobije jednolična i konzistentna masa. Plastični malter se nanosi pomoću ježa ili kompresora sa pištoljem. Prskanje se vrši 2-3 puta, odnosno da plastični malter ravnomerno pokrije površinu i da dobije jednoličan izgled u tonu i strukturi. Otvore i drugo zaštititi PVC folijom što ulazi u cenu, ali se otvori ne odbijaju od površine zidova."},
				"Obracun":  phi.F{"Obracun", "Text", "Obračun po m2 obrađene površine."},
				"Jedinica": phi.F{"Jedinica", "Text", "m2"},
				"Cena":     phi.F{"Cena", "Num", 3.50},
				"Slug":     phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_37"},
			},
		},
		38: phi.Φ{
			ID:       39,
			Category: "molerski_zidovi_i_plafoni",
			Struct: phi.S{
				"Title":    phi.F{"Title", "Text", "Obrada zidova plastičnim malterom (Bavalit) valjanjem."},
				"Opis":     phi.F{"Opis", "Text", "Vrsta i boje po izboru projektanta. Zidna podloga mora biti zdrava i suva. Podlogu očistiti i impregnirati izolacionom masom, radi bolje veze. Naneti molerskom četkom u jednom sloju, a ako podloga jako upija premazati dva puta. Na osušenu podlogu naneti malter, napravljen i dobro izmešan da se dobije jednolična i konzistentna masa. Plastični malter naneti gletelicom i strukturu izvući valjkom. Debljina nanetog sloja mora biti jednaka debljini, odnosno veličini zrna u plastičnom malteru. Otvore i drugo zaštititi PVC folijom što ulazi u cenu, ali se otvori ne odbijaju od površine zidova."},
				"Obracun":  phi.F{"Obracun", "Text", "Obračun po m2 obrađene površine."},
				"Jedinica": phi.F{"Jedinica", "Text", "m2"},
				"Cena":     phi.F{"Cena", "Num", 4.00},
				"Slug":     phi.F{"Slug", "Text", "molerski_zidovi_i_plafoni_38"},
			},
		},
	}
}
